import { Outfit, Playfair } from "next/font/google";
import "./globals.css";

const outfit = Outfit ({
  variable: "--font-outfit",
  subsets: ["latin"],
});

const playfair = Playfair ({
  variable: "--font-playfair",
  subsets: ["latin"],
});

export const metadata = {
  title: "STUDIO Barrasso",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="it">
      <body className={`${outfit.variable} ${playfair.variable} font-outfit w-screen h-screen`}>
        {children}
      </body>
    </html>
  );
}
